name: Deploy branch to Chalice

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies and project in dev mode
        run: |
          pip install 'chalice>=1.26.0,<1.27.0'
          pip install -r requirements.txt

      - name: Build in AWS
        run: |
          chalice package /tmp/packaged
          aws cloudformation package --template-file /tmp/packaged/sam.json --s3-bucket
                  ${APP_S3_BUCKET} --output-template-file transformed.yaml
